name: golden_test
description: Golden tests for dart
version: 1.0.0-1
homepage: https://github.com/matsp/golden_test

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  # build_config: ^1.1.1
  # build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
# dependencies:
  # analyzer: ^5.2.0
  # build: ^2.3.1
  # meta: ^1.8.0
  # source_gen: ^1.2.6
  # test_core: ^0.4.20
